# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
title: Esteb's blog
email: estebmaister@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome blog (I hope) to tell the adventures of a climber 
  and a coding enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://estebmaister.com.ve" # the base hostname & protocol for your site
twitter_username: Estebmaister
github_username: Estebmaister

# Build settings
markdown: kramdown
